### ISSUE TITLE
Does not install on macOS

### ISSUE THREAD

**Issue by fulldecent** [smart-on-fhir/health-cards-dev-tools#119]
It appears this application is shown as working on macOS. However, it will not install.

<img width="1250" alt="Screen Shot 2021-06-20 at 16 12 59" src="https://user-images.githubusercontent.com/382183/122687061-7757f800-d1e2-11eb-9c01-b4095ebb23e5.png">

Could instructions for macOS please be provided if this is a supported platform?

**Comment by christianpaquin** [comment]
Can you give details on your environment (OS, npm, and node versions)? Our CI [run tests](https://github.com/microsoft/health-cards-validation-SDK/blob/main/.github/workflows/node.js.yml) on `macos-latest` (which is [documented[(https://github.com/actions/virtual-environments) as macOS 10.5) with npm v14, 15, 16.

**Comment by fulldecent** [comment]
I am using a new Apple Silicon iMac with fresh Xcode, brew, node and NPM.

❯ node --version                  
v16.3.0

npm --version 
7.18.1

---

It appears the CI tests are only using the old Intel processor.

Root cause appears to be here https://github.com/Automattic/node-canvas/issues/1733

**Comment by christianpaquin** [comment]
Thanks for the info. If the issue is with a dependency, we'll have to wait for them to fix the package. Meanwhile, can you run the package from [docker](https://github.com/microsoft/health-cards-validation-SDK#running-in-docker)? Or perhaps use the [online portals](https://demo-portals.smarthealth.cards/)?

**Comment by fulldecent** [comment]
Thank you, the online portal is very helpful for me to see what was going on. This fully addresses what I was looking for.

I have been working on a competing blockchain-based project, https://genobank.io/certificates/, and wanted to see how SMART Health Cards works. Looks great!

**Comment by christianpaquin** [comment]
Let's keep this issue open until we get the SDK working on Apple M1; we might ping you again for a quick test once the canvas dependency has been fixed.

**Comment by fulldecent** [comment]
Sounds good

**Comment by christianpaquin** [comment]
I got access to a Mac Mini with a M1 processor; I can confirm I see the same error (with Darwin Kernel Version 20.5.0, npm v7.19.1, Node.js v16.5.0).

**Comment by ljoy913** [comment]
The issue of failed __canvas__ compilation should no longer occur as the __canvas__ package has been replaced in the project.  
Scanning the _package-lock.json_ file shows an optional peer-dependency still exists within the __jdom__ package (a dependency of Jest) - it appears __jsdom__ will use __canvas__, if installed, but will not install it as a dependency.
