### ISSUE TITLE
Validator should error out if payload is not trimmed

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/health-cards-dev-tools#145]
Example from https://chat.fhir.org/#narrow/stream/284830-smart.2Fhealth-cards/topic/How.20to.20register.20in.20the.20CommonTrust.20Network/near/250990464

```
shc:/5676295953265460346029254077280433602870286567675422280928623725376028702864716745222809286163393343320652240861444141373803087440031104414271373905440645243766402545604041280555632077452554774162327640626260573601062531315371707424357641442772412940673444046006342043093421362562734438002421395207702527743008247266520069285600626512593808632905032029085756307322584356103477587706040700572112207536580371403757696660223267330372377757666831036141300677757250057257300552320660047067203140672369453059525521097632217171632243410632596367577700414072325958400420565857445536067711346027505211123657437505234236664409356209534206731227552939347325367240270645373142265658206153663824717705050000666829245255736811204123627057303106343763077643706873563344536727602158122704365623573759123325556728237659732352245464352223704238326112114511236644312773676974364035743765583976762700083423037228373725677126200072275556243432064409362645103904111126053041776470377552070338770061523824413808576377333777606621070860554541340077345312400770613856693955732339557444290374323340606571113244062407317623565031372377722809241231373450232212311070347238320742403956252669077520275662424541447431585632005934256275037159613629420850341159254368620039255529102905053707596824607638313435674405110626355922392550307066255327057730326234677635355720376655347632656204540625055037444523640767053565384567053110045474084250094223045730705807715054082335343507262020235050743220013355583154246830052534317043656357586035292321255827610859441032095228404412353460412525095076293231325065296257702106407050740823305845303027417130033257273312095836126036
```

The demo portals happily accept this numeric QR payload, but shouldn't -- the payload contains a non-breaking space character as a prefix. We should be checking for something like:

    inflatedPayload.trim() === inflatedPayload

The validator succeeds because of https://github.com/smart-on-fhir/health-cards-validation-SDK/blob/60d9b366132ab7b7c296421e2da3fc81ff14c727/src/jws-payload.ts#L29 -- but I think this should be an error, not a warning. This is causing real-world scanning problems in at least one app, and I don't think our spec is lenient (or should be lenient) about allowing padding. Standard JSON parsers can deal with spaces and newlines, but choke on non-breaking spaces (which `trim()` eliminates).

Preferred solution: error out any time we don't have `inflatedPayload.trim() === inflatedPayload`

Alternative solution: warn when any padding is present, and also throw an error any time `JSON.parse(inflatedPayload)` (of the untrimmed payload) fails

**Comment by christianpaquin** [comment]
Fixed via #158 and in portal via [#68](https://github.com/smart-on-fhir/health-cards-tests/pull/68)
