### ISSUE TITLE
Factor out ssl

### ISSUE THREAD

**Issue by MoMannn** [smart-on-fhir/health-cards-dev-tools#161]
Factor out ssl to enable in browser use of this lib. Main problematic file:
https://github.com/smart-on-fhir/health-cards-dev-tools/blob/main/src/shcKeyValidator.ts

**Comment by christianpaquin** [comment]
Yes, we are aware that the dev tool doesn't work in the browser. The explicit goal of the project, as stated in the README, is to provide an _implementation_ validation tools, vs. a library that can be used to validate SMART Health Cards directly. Our [demo portals](https://demo-portals.smarthealth.cards/) allow developers to access functionality from a browser. What are you trying to accomplish from the browser beyond that?
