### ISSUE TITLE
Add pediatric CVX codes to usa-covid19-immunization profile

### ISSUE THREAD

**Issue by supersat** [smart-on-fhir/health-cards-dev-tools#170]
According to https://www.cdc.gov/vaccines/programs/iis/COVID-19-related-codes.html, it looks like the pediatric doses of Pfizer-BioNTech are 218 (for 10 mcg/0.2 mL, for ages 5-11), and 219 (3 mcg/0.2 mL, presumably for < 5 when approved).

If you scroll to the bottom of the page, 217 is also equivalent to 208. I'm not sure what the difference is there, except it might be for boosters?

At any rate, 217 and 218 should probably be added to cdcCovidCvxCodes and dcCovidAuthorizedCvxCodes starting here:

https://github.com/smart-on-fhir/health-cards-dev-tools/blob/7c9d9215c4d51239c962f18ce34c648b7c975a45/src/fhirBundle.ts#L16-L19

**Comment by jmandel** [comment]
Agreed 

* we should include `217`, `218`, `219` in `cdcCovidCvxCodes`
* we should also include `218` in the `cdcCovidAuthorizedCvxCodes` arrays, as it is currently approved and being administered (and I think it's fine to include `217` as well)
