### ISSUE TITLE
Suggestion: Warn when QR code JSON payload starts with UTF-8 BOM

### ISSUE THREAD

**Issue by LouisStAmour** [smart-on-fhir/health-cards-dev-tools#173]
Seems React Native's Hermes engine's JSON parsing has a bug where it can't parse a string that starts with a UTF-8 BOM. The error is not reproducible in Node.js here, so the QR code validates just fine and even in debug mode, no errors are visible.

This is one of the cases where, if unzipping with pako or similar, you might want to unzip not to string but to Uint8Array and then print out the hex... maybe. I never expected I would have to print out hexadecimal when working with simple JSON... :D

**Comment by christianpaquin** [comment]
Interesting; I had to [read up](https://www.w3.org/International/questions/qa-utf8-bom.en.html) on UTF-8 and BOM to understand this issue. I agree that a warning would be useful, especially since the [standard](https://www.unicode.org/versions/Unicode14.0.0/ch02.pdf) states that "Use of a BOM is neither required nor recommended for UTF-8".

**Comment by jmandel** [comment]
We have some related discussion at https://chat.fhir.org/#narrow/stream/284830-smart.2Fhealth-cards/topic/How.20to.20register.20in.20the.20CommonTrust.20Network/near/251260716 -- but looks like the checks I proposed were incomplete

**Comment by christianpaquin** [comment]
Should that be an error, rather than a warning?

**Comment by jmandel** [comment]
Yes, I believe so

**Comment by christianpaquin** [comment]
Interestingly, this situation was not caught by the fix for issue #145, because the BOM is stripped out when inflating directly to string with pake, as @LouisStAmour pointed out. I'll fix this, and add a unit test.

**Comment by LouisStAmour** [comment]
Actually, when converting to string pako doesn’t strip it exactly but Node.JS JSON.parse will not warn on it (it silently ignores it) and .trim() will strip it. I suggested using a raw buffer from pako if you want to display the hex when highlighting the presence of the UTF-8 BOM for example.

**Comment by jmandel** [comment]
> pako doesn’t strip it exactly but Node.JS JSON.parse will not warn on it (it silently ignores it)

Ah, interesting -- so my initial proposal of `inflatedPayload.trim() === inflatedPayload` may have been a valid check. In any case I agree that showing the hex would be helpful.

**Comment by christianpaquin** [comment]
Weird, the current code doesn't give a warning on such a sample, but splitting the parsing as bellow triggers the "JWS payload has leading or trailing spaces" error.
```
const inflatedPayloadBuf =  pako.inflateRaw(b64DecodedPayloadBuffer);
inflatedPayload = Buffer.from(inflatedPayloadBuf).toString();
```
I'm adding code to explicitly identify the BOM.

**Comment by LouisStAmour** [comment]
> I'm adding code to explicitly identify the BOM.

That’s my preference. It can be hard to identify the BOM as white space when it gets silently ignored by many text editors and such.
