### ISSUE TITLE
Suggestion: Error when short resource-scheme URIs are not used for references

### ISSUE THREAD

**Issue by LouisStAmour** [smart-on-fhir/health-cards-dev-tools#174]
http://hl7.org/fhir/uv/shc-vaccination/2021Sep/profiles.html#data-minimization says:

Implementers SHALL use `resource:0` syntax for IDs and references.

* Implementers SHALL populate `Bundle.entry.fullUrl` elements with short resource-scheme URIs (e.g., `{"fullUrl": "resource:0}`).
* Implementers SHALL populate `Reference.reference` elements with short resource-scheme URIs (e.g., `{"patient": {"reference": "resource:0"}}`) which SHALL resolve within the bundle.

I've seen issues where a QR code says, for example:

```
"patient": { "reference": "Patient/resource:0" },
```

And it's not flagged as an error or warning. All it says is "FHIR bundle validated"

**Comment by jmandel** [comment]
Thanks for this report! We should build a test case to catch this. If you're able to share (here or send me a PM on chat.fhir.org) where you've seen this in the wild, it'd be good for us to give a head up to these implementers.

**Comment by LouisStAmour** [comment]
Left a quick PM on chat.fhir.org, thanks. 👍

**Comment by ljoy913** [comment]
I found the issue with this.  A regex was allowing reference to be `<anytext>:#` instead of `resource:#` - I think I misunderstood the example in the spec to be similar to `resource:#` and not exactly `resource:#`
I have a fix for that and some additional checks, if I understand the requirements correctly:
- all `.fullUrl` and `.resource` fields are `resource:#`
- each `.fullUrl` is unique within the bundle
- each `reference: resource:#` refers to an existing `.fullUrl` within the bundle

**Comment by jmandel** [comment]
I think that looks right.  One piece to double check:

    >all .fullUrl and .resource fields

Did you mean `.reference` here instead of `.resource`?

**Comment by ljoy913** [comment]
Sorry, yes  `.reference` within a resource object - copy & paste error propagation :)

**Comment by ljoy913** [comment]
The '[02](https://spec.smarthealth.cards/examples/example-02-a-fhirBundle.json)' examples contains many reference like this:
```
        "performer": [
          {
            "reference": "Organization/1832473e-2fe0-452d-abe9-3cdb9879522f",
            "display": "Acme Laboratory, Inc"
          }
```
Should these also be `reference:#` ?

**Comment by jmandel** [comment]
Yeah, the 02 example is really just intended to show how splitting the JWS across QRs works; the actual data aren't particularly useful or correct (but it'd be fine to update the 02 example so it's not invalid ;-))
