### ISSUE TITLE
Does not install (test) or run on Mac OS 12.0.1

### ISSUE THREAD

**Issue by BiologyWorks** [smart-on-fhir/health-cards-dev-tools#178]
Followed steps exactly as described (see below) and it fails in Node not finding `cairo_fill` in the namespace. In addition, `npm update` fails due to version challenges with `jest` and `ts-jest`. It is an M1 Macbook Pro.

npm 8.1.4
node 17.0.1
MacOS 12.01

> `% **npm install**
> npm WARN old lockfile 
> npm WARN old lockfile The package-lock.json file was created with an old version of npm,
> npm WARN old lockfile so supplemental metadata must be fetched from the registry.
> npm WARN old lockfile 
> npm WARN old lockfile This is a one-time fix-up, please be patient...
> npm WARN old lockfile 
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> 
> > health-cards-dev-tools@1.1.1-2 prepare
> > npm run build
> 
> 
> > health-cards-dev-tools@1.1.1-2 build
> > tsc
> 
> 
> added 692 packages, and audited 693 packages in 18s
> 
> 64 packages are looking for funding
>   run `npm fund` for details
> 
> 7 moderate severity vulnerabilities
> 
> To address all issues, run:
>   npm audit fix
> 
> Run `npm audit` for details.
> % **npm run build**
> 
> > health-cards-dev-tools@1.1.1-2 build
> > tsc
> 
> % **npm test**
> 
> > health-cards-dev-tools@1.1.1-2 pretest
> > npm run fetch-examples && npm run fetch-profiles
> 
> 
> > health-cards-dev-tools@1.1.1-2 fetch-examples
> > ts-node --files src/fetch-examples.ts
> 
> Error: dlopen(/Users/pietro/Documents/Development/BiologyWorks/health-cards-dev-tools/node_modules/canvas/build/Release/canvas.node, 0x0001): symbol not found in flat namespace '_cairo_fill'
>     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1177:18)
>     at Module.load (node:internal/modules/cjs/loader:975:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:999:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/Users/pietro/Documents/Development/BiologyWorks/health-cards-dev-tools/node_modules/canvas/lib/bindings.js:3:18)
>     at Module._compile (node:internal/modules/cjs/loader:1095:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
>     at Module.load (node:internal/modules/cjs/loader:975:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> pietro@M1ProMaxNov2021 health-cards-dev-tools % 

`

**Comment by ljoy913** [comment]
__README.md__
> <h3>Prerequisites</h3>
>
> Make sure node.js and npm are installed on your system; the latest Long-Term Support (LTS) version is recommended for both (note that __node v16 is not currently supported__). OpenSSL 1.1.1 is also needed to validate certificate chains which could be present in issuer JSON Web Keys (x5c value); if absent, chain validation is skipped.

We'll update the README.md Prerequisites to change __node v16__ to __node v16+__

Thanks

**Comment by ljoy913** [comment]
We updated the version and did some package housekeeping.  See if this update resolves your issue.

**Comment by ljoy913** [comment]
The issue of failed __canvas__ compilation should no longer occur as the __canvas__ package has been replaced in the project.  
Scanning the _package-lock.json_ file shows an optional peer-dependency still exists within the __jdom__ package (a dependency of Jest) - it appears __jsdom__ will use __canvas__, if installed, but will not install it as a dependency.
