### ISSUE TITLE
Does every lab result SHC will always return a warning?

### ISSUE THREAD

**Issue by isaacvetter** [smart-on-fhir/health-cards-dev-tools#191]
Getting this error when attempting to [validate](https://demo-portals.smarthealth.cards/VerifierPortal.html) a lab result SHC:
>· JWS.payload.vc.type SHOULD NOT contain 'https://smarthealth.cards#covid19', no covid immunization or observation found (only CVX codes are currently recognized by the tool) (Warning)

I think the parenthetical "only CVX codes are currently recognized by the tool" means that this warning is not applicable. Is that right? Or is there a user error here?

We may finally be approaching the point when SHC lab tests will start to see significant usage. It would be nice if this awesome tool, created by intelligent, charismatic and good looking developers, returned accurate warnings/errors for lab tests.

Isaac

**Comment by christianpaquin** [comment]
I don't know about the good looking part :), but we sure want to make sure the tools are accurate! The tool will output this warning if the #covid19 label is used and no covid-related immunizations (from the CVX list) or observations (from the [loinc list](https://github.com/smart-on-fhir/health-cards-dev-tools/blob/09ae95f0dc8d08902ff8386f46f88c86de799f5a/src/fhirBundle.ts#L22)) are found (message isn't that clear!)

What codes are your lab result using?  Great if you can share the FHIR.

**Comment by jmandel** [comment]
Closing this as a stale issue. Please feel free to reopen if you have an example to share with surprising behavior!
