### ISSUE TITLE
How to Identify Booster dose cards.

### ISSUE THREAD

**Issue by purushothaman-k** [smart-on-fhir/health-cards-dev-tools#194]
How to differentiate between smart health cards which are having 1st or 2nd dose information with cards with booster dose information for same person.
Same user is having two different qr numeric for 1st/2nd dose and booster doses.

**Comment by jmandel** [comment]
https://build.fhir.org/ig/HL7/fhir-shc-vaccination-ig/ has profiling details; there's not a distinctive marker for "booster" per se; each dose conveys a vaccine product and date, and you can put together all the vaccine data that an individual chooses to share (from one or many SMART Health Cards) to build up a complete picture.
