### ISSUE TITLE
Feature request: "inspection" mode

### ISSUE THREAD

**Issue by jmandel** [smart-on-fhir/health-cards-dev-tools#42]
This could be a log level or (better still) a dedicated flag. I'd love to do things like printing a full JWS header + decompressed payload, for easy inspection.

**Comment by christianpaquin** [comment]
A lot of stuff is printed in the debug log level, I suppose it would be a good place to start (i.e., systematically add all the interim structures). Would you need a different output?

Also note the the dev portal in our [health-cards-tests fork](https://github.com/microsoft/health-cards-tests/tree/dev/demo) has some of that inspection capabilities.

**Comment by christianpaquin** [comment]
See PR #44 as stop-gap, adding missing JWS payload debug output (with `--loglevel debug`). Keeping think about cleaner output, possibly logging the payload to file like we do for the FHIR bundle

**Comment by jmandel** [comment]
Closing this for now -- `-l debug` has been good enough!
